CREATE DATABASE DienTuGiaDung2025;
GO
USE DienTuGiaDung2025;
GO

CREATE TABLE KhachHang (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    TenKH NVARCHAR(50) NOT NULL,
    GioiTinhKH INT NULL,
    SoDienThoaiKH VARCHAR(10) NOT NULL UNIQUE,
    EmailKH VARCHAR(100) NULL UNIQUE
);
GO

CREATE TABLE TaiKhoan (
    MaTK INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NULL UNIQUE,
    TenTK VARCHAR(20) NOT NULL UNIQUE,
    QuyenTK INT NOT NULL DEFAULT 0,
    MatKhauTK VARCHAR(255) NULL,
    NgayTaoTK DATETIME2 NOT NULL DEFAULT GETDATE(),
    NgayCapNhatTK DATETIME2 NOT NULL DEFAULT GETDATE(),
    TrangThaiTK INT NOT NULL DEFAULT 1,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);
GO

CREATE TABLE TinhThanhPho (
    MaTTP CHAR(2) PRIMARY KEY,
    TenTTP NVARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE XaPhuong (
    MaXP CHAR(5) PRIMARY KEY,
    MaTTP CHAR(2) NOT NULL,
    TenXP NVARCHAR(40) NOT NULL,
    FOREIGN KEY (MaTTP) REFERENCES TinhThanhPho(MaTTP)
);
GO

CREATE TABLE DiaChiCuThe (
    MaDCCT INT IDENTITY(1,1) PRIMARY KEY,
    MaXP CHAR(5) NOT NULL,
    MaKH INT NOT NULL,
    TenDCCT NVARCHAR(255) NOT NULL,
    MacDinhDCCT INT NOT NULL DEFAULT 0,
    FOREIGN KEY (MaXP) REFERENCES XaPhuong(MaXP),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);
GO

CREATE TABLE QuocGia (
    MaQG INT IDENTITY(1,1) PRIMARY KEY,
    TenQG NVARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE ThuongHieu (
    MaTH INT IDENTITY(1,1) PRIMARY KEY,
    MaQG INT NOT NULL,
    TenTH NVARCHAR(20) NOT NULL UNIQUE,
    FOREIGN KEY (MaQG) REFERENCES QuocGia(MaQG)
);
GO

CREATE TABLE LoaiSanPham (
    MaLSP INT IDENTITY(1,1) PRIMARY KEY,
    TenLSP NVARCHAR(40) NOT NULL UNIQUE,
    ThueGTGTLSP DECIMAL(4,2) NOT NULL DEFAULT 0,
    TrangThaiLSP INT NOT NULL DEFAULT 1
);
GO

CREATE TABLE SanPham (
    MaSP INT IDENTITY(1, 1) PRIMARY KEY,
    MaQG INT NULL,
    MaTH INT NULL,
    MaLSP INT NULL,
    TenSP NVARCHAR(100) NOT NULL,
    SoLuongSP INT NOT NULL DEFAULT 0,
    GiaNhapSP DECIMAL(10, 0) NOT NULL DEFAULT 0,
    GiaGocSP DECIMAL(10, 0) NOT NULL DEFAULT 0,
    PhanLoaiSP NVARCHAR(50) NULL,
    NamSanXuatSP INT NULL,
    BaoHanhSP NVARCHAR(255) NULL,
    KichThuocSP NVARCHAR(255) NULL,
    KhoiLuongSP NVARCHAR(100) NULL,
    CongSuatTieuThu NVARCHAR(10) NULL,
    ChatLieuSP NVARCHAR(255) NULL,
    TienIchSP NVARCHAR(500) NULL,
    CongNgheSP NVARCHAR(500) NULL,
    MucGiamGiaSP DECIMAL(4,2) NOT NULL DEFAULT 0,
    NgayHetGiamGiaSP DATETIME2 NULL,
    NgayTaoSP DATETIME2 NOT NULL DEFAULT GETDATE(),
    NgayCapNhatSP DATETIME2 NOT NULL DEFAULT GETDATE(),
    TrangThaiSP INT NOT NULL DEFAULT 1,
    FOREIGN KEY (MaQG) REFERENCES QuocGia(MaQG) ON DELETE SET NULL,
    FOREIGN KEY (MaTH) REFERENCES ThuongHieu(MaTH) ON DELETE SET NULL,
    FOREIGN KEY (MaLSP) REFERENCES LoaiSanPham(MaLSP) ON DELETE SET NULL
);
GO

CREATE TABLE Anh (
    MaAnh INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL,
    UrlAnh NVARCHAR(100) NOT NULL UNIQUE,
    MacDinhAnh INT NOT NULL DEFAULT 0,
    TrangThaiAnh INT NOT NULL DEFAULT 1,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE TrangThaiDonHang (
    MaTTDH INT PRIMARY KEY,
    TenTTDH NVARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE PhuongThucThanhToan (
    MaPTTT INT PRIMARY KEY,                     
    TenPTTT NVARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE DonHang (
    MaDH INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    SoTienDH DECIMAL(10,0) NOT NULL,
    PhiVanChuyenDH DECIMAL(10,0) NOT NULL,
    TongTienDH DECIMAL(10,0) NOT NULL,
    MaPTTT INT NOT NULL,
    MaTTDH INT NOT NULL,
    MaDCCT INT NOT NULL,
    NgayTaoDH DATETIME2 NOT NULL DEFAULT GETDATE(),
    NgayCapNhatDH DATETIME2 NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaPTTT) REFERENCES PhuongThucThanhToan(MaPTTT),
    FOREIGN KEY (MaTTDH) REFERENCES TrangThaiDonHang(MaTTDH)
    FOREIGN KEY (MaDCCT) REFERENCES DiaChiCuThe(MaDCCT),
);
GO

CREATE TABLE TrangThaiThanhToan (
    MaTTTT INT PRIMARY KEY,
    TenTTTT NVARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE ThanhToan (
    MaTT INT IDENTITY(1,1) PRIMARY KEY,
    MaDH INT NOT NULL,
    MaTTTT INT NOT NULL,
    MaGiaoDichTT NVARCHAR(30) NULL,
    NgayTaoTT DATETIME2 NOT NULL DEFAULT GETDATE(),
    NgayCapNhatTT DATETIME2 NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH) ON DELETE CASCADE,
    FOREIGN KEY (MaTTTT) REFERENCES TrangThaiThanhToan(MaTTTT)
);
GO

CREATE TABLE BaoGom (
    MaSP INT NOT NULL,
    MaDH INT NOT NULL,
    SoLuongDat INT NOT NULL,
    GiaDat DECIMAL(10,0) NOT NULL,
    ThueGTGTDat DECIMAL(4,2) NOT NULL,
    MucGiamGiaDat DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (MaSP, MaDH),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE,
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH) ON DELETE CASCADE
);
GO

CREATE TABLE MayLanh (
    MaML INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    CongSuatLamLanhML NVARCHAR(30) NULL,
    PhamViLamLanhML NVARCHAR(40) NULL,
    DoOnML NVARCHAR(50) NULL,
    LoaiGasML NVARCHAR(10) NULL,
    CheDoGioML NVARCHAR(60) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE TuLanh (
    MaTL INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    DungTichNganDaTL NVARCHAR(10) NULL,
    DungTichNganLanhTL NVARCHAR(10) NULL,
    LayNuocNgoaiTL NVARCHAR(10) NULL,
    LayDaTuDongTL NVARCHAR(10) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE NoiChien (
    MaNC INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    DungTichTongNC NVARCHAR(10) NULL,
    DungTichSuDungNC NVARCHAR(10) NULL,
    NhietDoNC NVARCHAR(20) NULL,
    HenGioNC NVARCHAR(20) NULL,
    BangDieuKhienNC NVARCHAR(50) NULL,
    ChieuDaiDayDienNC NVARCHAR(10) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE MayLocNuoc (
    MaMLN INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    KieuLapMLN NVARCHAR(30) NULL,
    CongSuatLocMLN NVARCHAR(30) NULL,
    TiLeLocThaiMLN NVARCHAR(30) NULL,
    ChiSoNuocMLN NVARCHAR(100) NULL,
    DoPHThucTeMLN NVARCHAR(100) NULL,
    ApLucNuocYeuCauMLN NVARCHAR(20) NULL,
    SoLoiLocMLN INT NULL,
    BangDieuKhienMLN NVARCHAR(40) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE TiVi (
    MaTV INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    CoManHinhTV NVARCHAR(10) NULL, 
    DoPhanGiaiTV NVARCHAR(10) NULL, 
    LoaiManHinhTV NVARCHAR(100) NULL, 
    TanSoQuetTV NVARCHAR(10) NULL, 
    DieuKhienTV NVARCHAR(100) NULL, 
    CongKetNoiTV NVARCHAR(100) NULL, 
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE NoiComDien (
    MaNCD INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    DungTichNCD NVARCHAR(10) NULL,
    ChucNangNCD NVARCHAR(255) NULL,
    DoDayNCD NVARCHAR(50) NULL,
    DieuKhienNCD NVARCHAR(50) NULL,
    ChieuDaiDayDienNCD NVARCHAR(10) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE MayLocKhongKhi (
    MaMLKK INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    LoaiBuiLocDuocMLKK NVARCHAR(100) NULL,
    PhamViLocMLKK NVARCHAR(10) NULL,
    LuongGioMLKK NVARCHAR(10) NULL,
    MangLocMLKK NVARCHAR(100) NULL,
    BangDieuKhienMLKK NVARCHAR(50) NULL,
    DoOnMLKK NVARCHAR(10) NULL,
    CamBienMLKK NVARCHAR(100) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE MayRuaChen (
    MaMRC INT IDENTITY(1,1) PRIMARY KEY,
    MaSP INT NOT NULL UNIQUE,
    NuocTieuThuMRC NVARCHAR(30) NULL,
    SoChenRuaDuocMRC NVARCHAR(30) NULL,
    DoOnMRC NVARCHAR(10) NULL,
    BangDieuKhienMRC NVARCHAR(50) NULL,
    ChieuDaiOngCapNuocMRC NVARCHAR(10) NULL,
    ChieuDaiOngThoatNuocMRC NVARCHAR(10) NULL,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE DanhGia (
    MaSP INT NOT NULL,
    MaKH INT NOT NULL,
    DiemDG INT NOT NULL,
    NhanXetDG NVARCHAR(255) NULL,
    NgayTaoDG DATETIME2 NOT NULL DEFAULT GETDATE(),
    NgayCapNhatDG DATETIME2 NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (MaSP, MaKH),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);
GO